package year2024day08

import (
	"testing"

	"github.com/polarfish/advent-of-code-go/tools/test"
)

var sample = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

func TestYear2024Day08Part1(t *testing.T) {
	test.Assert(t, "14", part1, sample)
	test.Assert(t, "269", part1, input)
}

func TestYear2024Day08Part2(t *testing.T) {
	test.Assert(t, "34", part2, sample)
	test.Assert(t, "949", part2, input)
}
