package year2025day07

import (
	"testing"

	"github.com/polarfish/advent-of-code-go/tools/test"
)

var sample = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`

func TestYear2025Day07Part1Sample(t *testing.T) {
	test.Assert(t, "21", part1, sample)
}

func TestYear2025Day07Part1(t *testing.T) {
	test.Assert(t, "1717", part1, input)
}

func TestYear2025Day07Part2Sample(t *testing.T) {
	test.Assert(t, "40", part2, sample)
}

func TestYear2025Day07Part2(t *testing.T) {
	test.Assert(t, "231507396180012", part2, input)
}
